baseURL = "https://jmramirez1204.github-io"
locale = "es"
title = "José Ramírez-Gómez"
theme = "PaperMod"

[params]
  ShowToc = true
  math = true

[markup.goldmark.extensions.passthrough]
  enable = true
  [markup.goldmark.extensions.passthrough.delimiters]
    block = [['$$', '$$'], ['\[', '\]']]
    inline = [['$', '$'], ['\(', '\)']]

[taxonomies]
  tag = "tags"
